### ISSUE TITLE
点击外链图片可能会卡死

### ISSUE THREAD

**Issue by lealife** [leanote/leanote-ios#13]
使用MarkDown编写笔记的时候，图片使用七牛云存储的外链，在IOS端点击图片的时候就会程序卡死。实际测试只使用Leanote或者其他外链（岛风外链：http://wailian.sob.hk/）的时候都不会出现。

**Comment by wongzigii** [comment]
Close as duplicate https://github.com/leanote/leanote-ios/issues/7
