### ISSUE TITLE
为啥不出安卓版的客户端？

### ISSUE THREAD

**Issue by LianGee** [leanote/leanote-ios#32]
求Android嘛

**Comment by dissipator** [comment]
就是啊，安卓用户也挺多的

**Comment by xingstarx** [comment]
还在完善中呢

**Comment by houxg** [comment]
@LianGee 
@dissipator 
@xingstarx 
我写了个第三方的Leanote Android客户端，欢迎试用, 戳[repo](https://github.com/houxg/Leamonax)

**Comment by xingstarx** [comment]
@houxg  看着很赞。。貌似看了下代码结构，跟官方的很多都很像啊。官方的代码结构需要好好改进额。。

**Comment by houxg** [comment]
@xingstarx 脱胎于官方repo，所以结构上以及一部分代码是来自于原版，各种改进之后觉得没法跟原版好好共处了就单独分出来了。
BTW谢谢你的可编译版本repo:)
