### ISSUE TITLE
Leanote iOS crashes on iPhone 6s upon inserting photo

### ISSUE THREAD

**Issue by mhoffmann75** [leanote/leanote-ios#34]
All the time inserting a photo leanote crashes:

After pressing the image plus icon leanote displays a black screen with the camera icon in the top left. After 1 second the photos from camera roll start to appear and a live camera picture is visible then leanote closes.

This happens reproducable on my device.

Device: iPhone 6s
iOS: 9.2.1 (latest)
App: 1.3 (latest from App Store)

**Comment by lealife** [comment]
Thanks, it has been fixed. But it hasn't been published on apple store yet.

**Comment by mhoffmann75** [comment]
Thanks @lealife ! Any plans when it will actually hit the app store? This is a show stopper for us :-(

**Comment by mhoffmann75** [comment]
Thanks its there :-)
