### ISSUE TITLE
最新包iOS下载后缺失pod

### ISSUE THREAD

**Issue by XiaoHanGe** [leanote/leanote-ios#46]
<img width="375" alt="d6e35258-dc51-4b55-a23e-eeaf81df7a20" src="https://cloud.githubusercontent.com/assets/14025157/21915325/290f2fbc-d974-11e6-96d6-18bfccfbd3aa.png">

**Comment by XiaoHanGe** [comment]
我简单的修改了一下，仅供参考！
<img width="739" alt="2017-01-13 10 02 00" src="https://cloud.githubusercontent.com/assets/14025157/21915837/6bb2b76e-d977-11e6-9de9-f0305fc431de.png">

**Comment by oday0311** [comment]
开发者 刚快 merge吧， 昨天我也改了一遍。 本地都跑不起来，

**Comment by lealife** [comment]
请发pull request, 不要发issue

**Comment by oday0311** [comment]
试了试， 除了这个 pod的问题，还有几个问题， LOG_LEVEL_DEF 为定义， 
<WordPress-iOS-Shared/WordPressShared/WPFontManager.h>找不到， 等， 建议你们先更新一下吧。目前用的xcode 8

**Comment by lealife** [comment]
@oday0311 xcode 7.3.1 没有这个问题. podfile已更新
