### ISSUE TITLE
iOS app无法以https方式连接到私服

### ISSUE THREAD

**Issue by andrewchenshx** [leanote/leanote-ios#48]
是否是因为SSL证书的原因？
web和desktop版本可以连接。

**Comment by juliusying** [comment]
Yes, 需要在手机上导入SSL证书才行

**Comment by andrewchenshx** [comment]
导入后仍然不行。报错界面无变化

Sent from my iPhone

On 28 Apr 2017, at 10:38 AM, juliusying <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, 需要在手机上导入SSL证书才行

**Comment by tossmilestone** [comment]
@juliusying 同样的问题，已经导入证书到ios中，还是出现登录错误提示，http可以登录

**Comment by zwd2zwd** [comment]
我也同样问题，怎么解决啊

**Comment by lealife** [comment]
使用免费的letsencrypt ssl
