### ISSUE TITLE
Build failed.

### ISSUE THREAD

**Issue by yayang** [leanote/leanote-ios#50]
After pod install，I got a Build failure，the information is “library not found for -lAFNetworking”
And I found that under .../Build/Products/Debug-iphoneos, there is no AFNetworking or other Pods dependencies (while it should exist).

Build Settings -> Library Search Paths, is generated by CocoaPods automatically.
Other linker Flags, is also default or automatically，including "-ObjC"

So, I wonder what I could do next to get the build success.

My environment is “OS X 10.12.5”，Xcode version is “8.3.3”，Build on "iPhone 6s（iOS 10.3.2）"and "simulator" both failed.

**Comment by Nsir15** [comment]
我也是遇到了这个问题。

**Comment by lealife** [comment]
https://github.com/leanote/leanote-ios/issues/60

**Comment by lealife** [comment]
https://stackoverflow.com/a/34258037/490844
