### ISSUE TITLE
build failer

### ISSUE THREAD

**Issue by liuweiju** [leanote/leanote-ios#51]
Target 'Pods-Leanote' of project 'Pods' was rejected as an implicit dependency for 'libPods-Leanote.a' because its architectures 'x86_64' didn't contain all required architectures 'i386'

**Comment by jingchangfa** [comment]
朋友你解决了么？同遇到，不知怎么解决。。。

**Comment by lealife** [comment]
ref https://github.com/leanote/leanote-ios/issues/60

**Comment by lealife** [comment]
https://stackoverflow.com/a/34258037/490844
