### ISSUE TITLE
编译失败！

### ISSUE THREAD

**Issue by 694718149** [leanote/leanote-ios#53]
clang: error: linker command failed with exit code 1 (use -v to see invocation)
估计是找不到libpods-Leanote.a的问题。希望知道怎么解决？非常感谢！

**Comment by jingchangfa** [comment]
朋友你解决了么？同遇到，不知怎么解决。。。

**Comment by 694718149** [comment]
没能解决~

**Comment by jiangxiaoxin** [comment]
同问

**Comment by lealife** [comment]
ref https://github.com/leanote/leanote-ios/issues/60
