### ISSUE TITLE
WordPress-iOS-Shared has been deprecated

### ISSUE THREAD

**Issue by wangjinlei1223** [leanote/leanote-ios#60]
pod install 的时候提示WordPress-iOS-Shared has been deprecated
运行的时候提示很多WordPress-iOS-Shared头文件找不到

**Comment by ocbear** [comment]
我也是遇到这个，估计这个库挂了吧，不知道从哪里可以下载

**Comment by lealife** [comment]
@wangjinlei1223 @ocbear 我已将我本地的Pods上传, 希望能有用到 https://github.com/leanote/leanote-ios/tree/release/Pods-bak 
如果有用, 还望能说声

**Comment by lealife** [comment]
重新pull下仓库, 然后
```
delete -rf Pods
pod install
```
双击 `Leanote.xcworkspace` 运行即可
